/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pecdeck.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PecDeck(props) {
  const { nodes, materials } = useGLTF('/pecdeck.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Line02.geometry} material={nodes.Line02.material} />
      <mesh geometry={nodes.Object01.geometry} material={nodes.Object01.material} />
      <mesh geometry={nodes.Line05.geometry} material={nodes.Line05.material} />
      <mesh geometry={nodes.efefe.geometry} material={nodes.efefe.material} />
      <mesh geometry={nodes.ChamferBox01.geometry} material={nodes.ChamferBox01.material} />
      <mesh geometry={nodes.ChamferBox02.geometry} material={nodes.ChamferBox02.material} />
      <mesh geometry={nodes.ChamferBox07.geometry} material={nodes.ChamferBox07.material} />
      <mesh geometry={nodes.ChamferBox08.geometry} material={nodes.ChamferBox08.material} />
      <mesh geometry={nodes.Line06.geometry} material={nodes.Line06.material} />
      <mesh geometry={nodes.ChamferBox18.geometry} material={nodes.ChamferBox18.material} />
      <mesh geometry={nodes.hrom001.geometry} material={nodes.hrom001.material} />
      <mesh geometry={nodes.Line021.geometry} material={nodes.Line021.material} />
      <mesh geometry={nodes.rgrg.geometry} material={nodes.rgrg.material} />
      <mesh geometry={nodes.Line022.geometry} material={nodes.Line022.material} />
      <mesh geometry={nodes.ChamferBox019.geometry} material={nodes.ChamferBox019.material} />
      <mesh geometry={nodes.Cylinder077.geometry} material={nodes.Cylinder077.material} />
      <mesh geometry={nodes.fixator006_Retopo005.geometry} material={nodes.fixator006_Retopo005.material} />
      <mesh geometry={nodes.Object009.geometry} material={nodes.Object009.material} />
      <mesh geometry={nodes.sxema001.geometry} material={nodes.sxema001.material} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} />
      <mesh geometry={nodes.Box029.geometry} material={nodes.Box029.material} />
      <mesh geometry={nodes.Box028.geometry} material={nodes.Box028.material} />
      <mesh geometry={nodes.Box027.geometry} material={nodes.Box027.material} />
      <mesh geometry={nodes.Box026.geometry} material={nodes.Box026.material} />
      <mesh geometry={nodes.Box025.geometry} material={nodes.Box025.material} />
      <mesh geometry={nodes.Box024.geometry} material={nodes.Box024.material} />
      <mesh geometry={nodes.Box023.geometry} material={nodes.Box023.material} />
      <mesh geometry={nodes.Box022.geometry} material={nodes.Box022.material} />
      <mesh geometry={nodes.Box021.geometry} material={nodes.Box021.material} />
      <mesh geometry={nodes.Box020.geometry} material={nodes.Box020.material} />
      <mesh geometry={nodes.Box048.geometry} material={nodes.Box048.material} />
      <mesh geometry={nodes.Box018.geometry} material={nodes.Box018.material} />
      <mesh geometry={nodes.Line050.geometry} material={nodes.Line050.material} />
      <mesh geometry={nodes.ChamferBox028.geometry} material={nodes.ChamferBox028.material} />
      <mesh geometry={nodes.Line052.geometry} material={nodes.Line052.material} />
      <mesh geometry={nodes.Cylinder079.geometry} material={nodes.Cylinder079.material} />
      <mesh geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} />
      <mesh geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} />
      <mesh geometry={nodes.ChamferCyl044.geometry} material={nodes.ChamferCyl044.material} />
      <mesh geometry={nodes.ChamferCyl048.geometry} material={nodes.ChamferCyl048.material} />
      <mesh geometry={nodes.Cylinder091.geometry} material={nodes.Cylinder091.material} />
      <mesh geometry={nodes.Sphere017.geometry} material={nodes.Sphere017.material} />
      <mesh geometry={nodes.Sphere018.geometry} material={nodes.Sphere018.material} />
      <mesh geometry={nodes.Sphere014.geometry} material={nodes.Sphere014.material} />
      <mesh geometry={nodes.ChamferCyl043.geometry} material={nodes.ChamferCyl043.material} />
      <mesh geometry={nodes.Cylinder078.geometry} material={nodes.Cylinder078.material} />
      <mesh geometry={nodes.Sphere013.geometry} material={nodes.Sphere013.material} />
      <mesh geometry={nodes.Line053.geometry} material={nodes.Line053.material} />
      <mesh geometry={nodes.Line054.geometry} material={nodes.Line054.material} />
      <mesh geometry={nodes.Object020.geometry} material={nodes.Object020.material} />
      <mesh geometry={nodes.Line17.geometry} material={nodes.Line17.material} />
      <mesh geometry={nodes.ChamferCyl02.geometry} material={nodes.ChamferCyl02.material} />
      <mesh geometry={nodes.Object02.geometry} material={nodes.Object02.material} />
      <mesh geometry={nodes.ChamferCyl41.geometry} material={nodes.ChamferCyl41.material} />
      <mesh geometry={nodes.ChamferCyl049.geometry} material={nodes.ChamferCyl049.material} />
      <mesh geometry={nodes.ChamferCyl050.geometry} material={nodes.ChamferCyl050.material} />
      <mesh geometry={nodes.Line055.geometry} material={nodes.Line055.material} />
      <mesh geometry={nodes.Object021.geometry} material={nodes.Object021.material} />
      <mesh geometry={nodes.Object022.geometry} material={nodes.Object022.material} />
      <mesh geometry={nodes.ChamferCyl051.geometry} material={nodes.ChamferCyl051.material} />
      <mesh geometry={nodes.Cylinder092.geometry} material={nodes.Cylinder092.material} />
      <mesh geometry={nodes.Sphere019.geometry} material={nodes.Sphere019.material} />
      <mesh geometry={nodes.Sphere020.geometry} material={nodes.Sphere020.material} />
      <mesh geometry={nodes.Line056.geometry} material={nodes.Line056.material} />
      <mesh geometry={nodes.rfgrgr.geometry} material={nodes.rfgrgr.material} />
      <mesh geometry={nodes.rgrgr.geometry} material={nodes.rgrgr.material} />
      <mesh geometry={nodes.Object023.geometry} material={nodes.Object023.material} />
      <mesh geometry={nodes.bfdrb.geometry} material={nodes.bfdrb.material} />
      <mesh geometry={nodes.fvbrb.geometry} material={nodes.fvbrb.material} />
      <mesh geometry={nodes.fvrv.geometry} material={nodes.fvrv.material} />
      <mesh geometry={nodes.Cylinder093.geometry} material={nodes.Cylinder093.material} />
      <mesh geometry={nodes.fixator006_Retopo006.geometry} material={nodes.fixator006_Retopo006.material} />
      <mesh geometry={nodes.Cylinder094.geometry} material={nodes.Cylinder094.material} />
      <mesh geometry={nodes.fixator006_Retopo007.geometry} material={nodes.fixator006_Retopo007.material} />
      <mesh geometry={nodes.Box049.geometry} material={nodes.Box049.material} />
      <mesh geometry={nodes.Object024.geometry} material={nodes.Object024.material} />
      <mesh geometry={nodes.Box050.geometry} material={nodes.Box050.material} />
      <mesh geometry={nodes.Object025.geometry} material={nodes.Object025.material} />
    </group>
  )
}

useGLTF.preload('/pecdeck.gltf')
